-- Rebuild Database Script

-- Step 1: Drop existing tables and types if they exist
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;
DROP TYPE IF EXISTS public."account_type";

-- Step 2: Create ENUM type for account_type
CREATE TYPE public."account_type" AS ENUM
    ('Client', 'Employee', 'Admin');
ALTER TYPE public."account_type"
    OWNER TO cse340_database_izqj_user;

-- Step 3: Create the classification table
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_name CHARACTER VARYING NOT NULL
);

-- Step 4: Create the inventory table
CREATE TABLE public.inventory (
    inventory_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_id INT NOT NULL,
    make CHARACTER VARYING NOT NULL,
    model CHARACTER VARYING NOT NULL,
    description CHARACTER VARYING,
    inv_image CHARACTER VARYING,
    inv_thumbnail CHARACTER VARYING,
    CONSTRAINT inventory_fk FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id)
);

-- Step 5: Create the account table
CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name CHARACTER VARYING NOT NULL,
    last_name CHARACTER VARYING NOT NULL,
    email CHARACTER VARYING NOT NULL UNIQUE,
    password CHARACTER VARYING NOT NULL,
    account_type public."account_type" DEFAULT 'Client'
);

-- Step 6: Populate the classification table
INSERT INTO public.classification (classification_name)
VALUES 
    ('Sport'),
    ('SUV'),
    ('Sedan'),
    ('Truck');

-- Step 7: Populate the inventory table
INSERT INTO public.inventory (classification_id, make, model, description, inv_image, inv_thumbnail)
VALUES 
    (1, 'Ford', 'Mustang', 'A powerful sports car', '/images/ford-mustang.jpg', '/images/thumbnails/ford-mustang.jpg'),
    (1, 'Chevrolet', 'Camaro', 'A sleek and stylish car', '/images/chevrolet-camaro.jpg', '/images/thumbnails/chevrolet-camaro.jpg'),
    (2, 'GM', 'Hummer', 'Small interiors', '/images/gm-hummer.jpg', '/images/thumbnails/gm-hummer.jpg');

-- Step 8: Queries to update data as per assignment requirements

-- Modify the "GM Hummer" record's description to replace "small interiors" with "a huge interior"
UPDATE public.inventory
SET description = REPLACE(description, 'small interiors', 'a huge interior')
WHERE make = 'GM' AND model = 'Hummer';

-- Update all records in the "inventory" table to add "/vehicles" to the middle of file paths
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

-- Validation query (optional): Retrieve all records from inventory table
SELECT * FROM public.inventory;
