-- Create ENUM type for account_type
CREATE TYPE public."account_type" AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public."account_type"
    OWNER TO cse340_database_izqj_user;

-- Table structure for table `classification`
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Table structure for table `inventory`
CREATE TABLE public.inventory (
    inventory_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_id INT NOT NULL,
    make CHARACTER VARYING NOT NULL,
    model CHARACTER VARYING NOT NULL,
    description CHARACTER VARYING,
    inv_image CHARACTER VARYING,
    inv_thumbnail CHARACTER VARYING,
    CONSTRAINT inventory_pk PRIMARY KEY (inventory_id),
    CONSTRAINT inventory_fk FOREIGN KEY (classification_id)
        REFERENCES public.classification(classification_id)
);

-- Table structure for table `account`
CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name CHARACTER VARYING NOT NULL,
    last_name CHARACTER VARYING NOT NULL,
    email CHARACTER VARYING NOT NULL UNIQUE,
    password CHARACTER VARYING NOT NULL,
    account_type public."account_type" DEFAULT 'Client',
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);

-- Populate the `classification` table
INSERT INTO public.classification (classification_name)
VALUES
    ('Sport'),
    ('SUV'),
    ('Sedan'),
    ('Truck');

-- Populate the `inventory` table
INSERT INTO public.inventory (classification_id, make, model, description, inv_image, inv_thumbnail)
VALUES
    (1, 'Ford', 'Mustang', 'A powerful sports car', '/images/ford-mustang.jpg', '/images/thumbnails/ford-mustang.jpg'),
    (1, 'Chevrolet', 'Camaro', 'A sleek and stylish car', '/images/chevrolet-camaro.jpg', '/images/thumbnails/chevrolet-camaro.jpg'),
    (2, 'GM', 'Hummer', 'Small interiors', '/images/gm-hummer.jpg', '/images/thumbnails/gm-hummer.jpg');

-- Queries from Task 1: Query 4
-- Modify the "GM Hummer" record's description to replace "small interiors" with "a huge interior"
UPDATE inventory
SET description = REPLACE(description, 'small interiors', 'a huge interior')
WHERE make = 'GM' AND model = 'Hummer';

-- Queries from Task 1: Query 6
-- Update all records in the "inventory" table to add "/vehicles" to the middle of file paths
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
